name: Commit to Different Repo

on:
  push:
    branches:
      - main

permissions: 
  contents: write

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

      
    - name: Create Repository from Template
      env:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        REPO_NAME=Hello-World2 
        ORG_NAME=oliveiridis
        response=$(curl -v -L \
          -X PUT \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $PAT_TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/$ORG_NAME/$REPO_NAME/actions/permissions/workflow \
        -d '{"default_workflow_permissions":"write","can_approve_pull_request_reviews":true}')

    - name: Configure Git
      run: |
        git config user.name "Your GitHub Username"
        git config user.email "vito_oli@hotmail.com"
        git remote add target-repo https://github.com/oliveiridis/Hello-World2.git
        git fetch target-repo
        
        
    - name: Clone the source repository
      run: |
        git clone https://github.com/oliveiridis/Hello-World.git
        git remote -v
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_token }}

    - name: Copy source repository contents to same repository
      run: |
        ls -l
        cp -r Hello-World/* .
        #git add .
        #git commit -m "Copy contents from source repository"
        #git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_token }}

    - name: Copy source repository target to same repository
      run: |
        cp -r Hello-World/* .
        git remote -v
        git add .
        git status
        #git commit -m "Auto commit by GitHub Actions"
        #git push https://github.com/oliveiridis/Hello-World2.git main
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_token }}

    - name: Pushes check
      run: git config --global --add safe.directory '*'
      
    - name: Pushes test folder
      uses: datalbry/copy_folder_to_another_repo_action@1.0.0
      env:
        API_TOKEN_GITHUB: ${{ secrets.PAT_token }}
      with:
        source_folder: 'Hello-World'
        destination_repo: 'oliveiridis/Hello-World2'
        destination_folder: ''
        user_email: 'vito.oli@hotmail.com'
        destination_branch: 'main'
        user_name: 'oliveiridis'
        commit_msg: '[GHA] Update the test files.'
    
        
