name: Commit to Different Repo

on:
  push:
    branches:
      - main

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Configure Git
      run: |
        git config user.name "Your GitHub Username"
        git config user.email "vitor.oliveira@hotmail.com"
        git remote add target-repo https://github.com/oliveiridis/Hello-World2.git
        git fetch target-repo
        
    - name: Clone the source repository
      run: |
        git clone https://github.com/oliveiridis/Hello-World.git
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_token }}

    - name: Copy source repository contents to same repository
      run: |
        ls -l
        cp -r Hello-World/* .
        #git add .
        #git commit -m "Copy contents from source repository"
        #git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_token }}
    
    - name: Copy source repository target to same repository
      run: |
        ls
        git status
        git checkout -b new branch
        cp -r Hello-World/* .
        ls
        git remote -v
        git add .
        git status
        git commit -m "Auto commit by GitHub Actions"
        git push target-repo new branch
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_token }}
        
