
name: Add Secret to Repository

on:
  push:
    branches:
      - main  # Adjust this to your main branch name

jobs:
  add-secret:
    runs-on: ubuntu-latest

    steps:
    
      - name: cache octosecret
        id: cache-octosecret
        uses: actions/cache@v1
        with:
          path: /usr/bin/octosecret
          key: ${{ runner.os }}-octosecret

      - name: download octosecret
        if: steps.cache-octosecret.outputs.cache-hit != 'true'
        run: |
          sudo curl -sL https://github.com/ceejbot/octosecret/releases/download/v0.1.0/octosecret_linux_x64 -o /usr/bin/octosecret
          sudo chmod +x /usr/bin/octosecret

      - name: Get public key
        id: public-key
        run: |
          TOKEN="${{ secrets.PAT_TOKEN }}"
          REPO_OWNER="oliveiridis"
          REPO_NAME="Hello-World2"

          PUBLIC_KEY_RESPONSE=$(curl -X GET -H "Authorization: token $TOKEN" -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/actions/secrets/public-key")

          PUBLIC_KEY=$(echo $PUBLIC_KEY_RESPONSE | jq -r .key)
          KEY_ID=$(echo $PUBLIC_KEY_RESPONSE | jq -r .key_id)

          echo $PUBLIC_KEY >> public-key.json
          echo $KEY_ID >> key-id.txt

        env:
          GITHUB_PAT: ${{ secrets.GITHUB_PAT }}

      - name: Add Secret
        run: |
          TOKEN="${{ secrets.PAT_TOKEN }}"
          REPO_OWNER="oliveiridis"
          REPO_NAME="Hello-World2"
          SECRET_NAME="PAT_TOKEN"
          SECRET_VALUE="$TOKEN"

          PUBLIC_KEY=$(cat public-key.json)
          KEY_ID=$(cat key-id.txt)

          ENCRYPTED_SECRET=$(echo -n "$SECRET_VALUE" | openssl rsautl -encrypt -pubin -inkey <(echo "$PUBLIC_KEY") | base64)

          RESPONSE=$(curl -X PUT -H "Authorization: token $TOKEN" -H "Accept: application/vnd.github.v3+json" \
            -d '{"encrypted_value": "'"$ENCRYPTED_SECRET"'", "key_id": "'"$KEY_ID"'""}' \
            "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/actions/secrets/$SECRET_NAME")

          echo $RESPONSE

        env:
          GITHUB_PAT: ${{ secrets.PAT_TOKEN }}
