name: Add Secret to Repository

on:
  push:
    branches:
      - main  # Adjust this to your main branch name

jobs:
  add-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install @actions/core @actions/github got

      - name: Get public key
        id: public-key
        run: |
          TOKEN="${{ secrets.GITHUB_PAT }}"
          REPO_OWNER="your-username"
          REPO_NAME="your-repo-name"

          PUBLIC_KEY_RESPONSE=$(curl -X GET -H "Authorization: token $TOKEN" -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/actions/secrets/public-key")

          PUBLIC_KEY=$(echo $PUBLIC_KEY_RESPONSE | jq -r .key)
          KEY_ID=$(echo $PUBLIC_KEY_RESPONSE | jq -r .key_id)

          echo $PUBLIC_KEY >> public-key.json
          echo $KEY_ID >> key-id.txt

        env:
          GITHUB_PAT: ${{ secrets.GITHUB_PAT }}

      - name: Add Secret
        run: |
          TOKEN="${{ secrets.GITHUB_PAT }}"
          REPO_OWNER="your-username"
          REPO_NAME="your-repo-name"
          SECRET_NAME="your-secret-name"
          SECRET_VALUE="your-secret-value"

          PUBLIC_KEY=$(cat public-key.json)
          KEY_ID=$(cat key-id.txt)

          ENCRYPTED_SECRET=$(echo -n "$SECRET_VALUE" | openssl rsautl -encrypt -pubin -inkey <(echo "$PUBLIC_KEY") | base64)

          RESPONSE=$(curl -X PUT -H "Authorization: token $TOKEN" -H "Accept: application/vnd.github.v3+json" \
            -d "{\"encrypted_value\":\"$ENCRYPTED_SECRET\",\"key_id\":\"$KEY_ID\"}" \
            "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/actions/secrets/$SECRET_NAME")

          echo $RESPONSE

        env:
          GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
