name: Add Secret 2

on:
  push:
    branches:
      - main  # Adjust this to your main branch name

jobs:
  add-secret:
    runs-on: ubuntu-latest

    steps:
    
      - name: cache octosecret
        id: cache-octosecret
        uses: actions/cache@v1
        with:
          path: /usr/bin/octosecret
          key: ${{ runner.os }}-octosecret

      - name: download octosecret
        if: steps.cache-octosecret.outputs.cache-hit != 'true'
        run: |
          sudo curl -sL https://github.com/ceejbot/octosecret/releases/download/v0.1.0/octosecret_linux_x64 -o /usr/bin/octosecret
          sudo chmod +x /usr/bin/octosecret

      - name: Get public key
        id: public-key
        run: |
          TOKEN="${{ secrets.PAT_TOKEN }}"
          REPO_OWNER="oliveiridis"
          REPO_NAME="Hello-World2"
          SECRET_NAME="PAT_TOKEN"
          SECRET_VALUE="$TOKEN"

          key_data=$(curl -s -H "Accept: application/vnd.github.mercy-preview+json" -H "Authorization: token ${{ secrets.PAT_TOKEN }}" 'https://api.github.com/repos/'"$REPO_OWNER"'/'"$REPO_NAME"'/actions/secrets/public-key')
          
          key_id=$(jq -r '.key_id' <<< "$key_data")
          key_b64=$(jq -r '.key' <<< "$key_data")

          
          encrypted_value=$(printf "%s" "$TOKEN" | octosecret "$key_b64")

          result=0; curl -sf \
                -X PUT \
                -d '{"encrypted_value": "'"$encrypted_value"'", "key_id": "'"$key_id"'"}' \
                -H "Accept: application/vnd.github.mercy-preview+json" \
                -H "Content-Type: application/json" \
                -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
                'https://api.github.com/repos/'"$REPO_OWNER"'/'"$REPO_NAME"'/actions/secrets/'"$SECRET_NAME"' || result=$?
                         
            
        env:
          GITHUB_PAT: ${{ secrets.PAT_TOKEN }}
